# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - Third Iteration 2024.1 

In [1]:
#pip install nbconvert pip install pyppeteer

In [2]:
#--allow-chromium-download

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [3]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [4]:
# 1. Create an array of 10 ones
array_of_ones = np.ones(10)
print("Array of 10 ones:")
print(array_of_ones)

# 2. Create an array of the integers 1 to 20
array_1_to_20 = np.arange(1, 21)
print("\nArray of integers 1 to 20:")
print(array_1_to_20)

# 3. Create a 5 x 5 matrix of ones with dtype int
matrix_5x5_ones = np.ones((5, 5), dtype=int)
print("\n5 x 5 matrix of ones with dtype int:")
print(matrix_5x5_ones)

Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of integers 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

5 x 5 matrix of ones with dtype int:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [5]:
# 1. Create a 3D matrix of shape 3 x 3 x 3 with random numbers from a standard normal distribution
matrix_3x3x3 = np.random.randn(3, 3, 3)
print("3D matrix of shape 3 x 3 x 3 with random numbers:")
print(matrix_3x3x3)

# 2. Reshape the above array into shape (27,)
reshaped_array = matrix_3x3x3.reshape(27)
print("\nReshaped array with shape (27,):")
print(reshaped_array)

3D matrix of shape 3 x 3 x 3 with random numbers:
[[[-0.89247852  0.2904345   0.80355419]
  [ 0.58152035  1.01112056 -0.67698956]
  [ 0.8929459  -1.7264965   1.42850032]]

 [[-0.83880868  0.7367674   0.3107399 ]
  [-0.89974432 -1.82600067 -0.94294402]
  [ 1.10005068 -3.2231896   1.16998582]]

 [[ 0.67858981  1.57193181  1.57009982]
  [-0.53806916 -2.38716115  0.45904339]
  [-0.54803935  0.16914292 -0.17325049]]]

Reshaped array with shape (27,):
[-0.89247852  0.2904345   0.80355419  0.58152035  1.01112056 -0.67698956
  0.8929459  -1.7264965   1.42850032 -0.83880868  0.7367674   0.3107399
 -0.89974432 -1.82600067 -0.94294402  1.10005068 -3.2231896   1.16998582
  0.67858981  1.57193181  1.57009982 -0.53806916 -2.38716115  0.45904339
 -0.54803935  0.16914292 -0.17325049]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [6]:
# Create an array of 20 linearly spaced numbers between 1 and 10
linear_space_array = np.linspace(1, 10, 20)
print("Array of 20 linearly spaced numbers between 1 and 10:")
print(linear_space_array)

Array of 20 linearly spaced numbers between 1 and 10:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [7]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [10]:
20

20

In [11]:
subarray = a[1:, 3:]
print(subarray)

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [13]:
row_array = a[1, :]
print(row_array)


[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [14]:
total_sum = np.sum(a)
print(total_sum)

325


## 2.6 

Calculate the sum of each row in `a`.

In [15]:
row_sums = np.sum(a, axis=1)
print(row_sums)

[ 15  40  65  90 115]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [17]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

# Calculate the mean of 'a'
mean_value = np.mean(a)

# Create a boolean mask for values greater than the mean
mask = a > mean_value

# Extract values using the boolean mask
values_greater_than_mean = a[mask]

print("Mean value:", mean_value)
print("Values greater than the mean:")
print(values_greater_than_mean)

Mean value: 13.0
Values greater than the mean:
[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [18]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [20]:


# URL of the dataset
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

# Import the dataset as a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame and the columns for verification
print(df.head())
print("\nColumns in the DataFrame:")
print(df.columns)

     country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96

Columns in the DataFrame:
Index(['country', 'food_category', 'consumption', 'co2_emmission'], dtype='object')


## 2.10 

How many rows and columns are there in the dataframe?

In [21]:
# URL of the dataset
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

# Import the dataset as a DataFrame
df = pd.read_csv(url)

# Get the number of rows and columns
num_rows, num_columns = df.shape

print(f"The DataFrame has {num_rows} rows and {num_columns} columns.")

The DataFrame has 1430 rows and 4 columns.


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [22]:
# URL of the dataset
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

# Import the dataset as a DataFrame
df = pd.read_csv(url)

# Calculate the mean of the 'co2_emmission' column
mean_co2_emission = df['co2_emmission'].mean()

print(f"The mean CO2 emission of the whole dataset is: {mean_co2_emission:.2f} kg CO2/person/year")

The mean CO2 emission of the whole dataset is: 74.38 kg CO2/person/year


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [23]:
df = pd.read_csv(url)

# Find the row with the maximum co2_emmission
max_co2_row = df.loc[df['co2_emmission'].idxmax()]

# Extract the maximum co2_emmission, food category, and country
max_co2_emission = max_co2_row['co2_emmission']
food_category = max_co2_row['food_category']
country = max_co2_row['country']

print(f"The maximum CO2 emission in the dataset is: {max_co2_emission} kg CO2/person/year")
print(f"It belongs to the food type: {food_category} in country: {country}.")

The maximum CO2 emission in the dataset is: 1712.0 kg CO2/person/year
It belongs to the food type: Beef in country: Argentina.


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [24]:
df = pd.read_csv(url)

# Filter countries with CO2 emissions greater than 1000 kg/person/year
high_emission_countries = df[df['co2_emmission'] > 1000]['country'].unique()

# Count the number of unique countries
num_countries = len(high_emission_countries)

print(f"The number of countries producing more than 1000 kg CO2/person/year for at least one food type is: {num_countries}")

The number of countries producing more than 1000 kg CO2/person/year for at least one food type is: 5


## 2.14

Which country consumes the least amount of beef per person per year?


In [25]:
df = pd.read_csv(url)

# Filter for beef consumption
beef_consumption = df[df['food_category'] == 'Beef']

# Find the country with the minimum beef consumption
min_beef_row = beef_consumption.loc[beef_consumption['consumption'].idxmin()]

# Extract information
min_beef_consumption = min_beef_row['consumption']
country = min_beef_row['country']

print(f"The country that consumes the least amount of beef per person per year is: {country} with {min_beef_consumption} kg/person/year.")

The country that consumes the least amount of beef per person per year is: Liberia with 0.7799999999999999 kg/person/year.


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [27]:
df = pd.read_csv(url)

# List of meat categories to consider
meat_categories = ['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']

# Filter for meat products and calculate total emissions
total_meat_emissions = df[df['food_category'].isin(meat_categories)]['co2_emmission'].sum()

print(f"The total emissions of all meat products in the dataset combined is: {total_meat_emissions} kg CO2/person/year.")


The total emissions of all meat products in the dataset combined is: 74441.13 kg CO2/person/year.


# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [30]:
df = pd.read_csv(url)

meat_categories = ['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']

total_non_meat_emissions = df[~df['food_category'].isin(meat_categories)]['co2_emmission'].sum()

print(f"The total emissions of all non-meat products in the dataset combined is: {total_non_meat_emissions} kg CO2/person/year.")

The total emissions of all non-meat products in the dataset combined is: 31927.98 kg CO2/person/year.


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.